### ISSUE TITLE
How can I haddle on a deprecated error?

### ISSUE THREAD

**Issue by sole-dev** [lydell/urix#4]
I installed urix by npm, but it warned, `npm warn deprecated urix@0.1.0`. How can I solve it?

**Comment by lydell** [comment]
Hi! In the deprecation message there is also a link. Did you follow it and read what’s there?

**Comment by NewProgrammer1234** [comment]
I saw the deprecated message, but I can't understand the message. I am curious about installing the urix package alone, without packages like source-map-resolve. Could you explain me about it in detail?

**Comment by lydell** [comment]
Thanks! When a package is deprecated, it means that the author does not think it should be used anymore. I don’t like this package. In https://github.com/lydell/source-map-resolve/issues/9 I learned that converting Windows paths isn’t as easy as thin module makes it look. So I recommend doing it some other way. For starters, you could copy the ~5 lines of code of this module into your code instead of installing this package.

**Comment by NewProgrammer1234** [comment]
Thanks for your help! I should have to find out a new way for my project.
